version: 2.1

jobs:
  test:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby_version >>
    steps:
      - checkout
      - restore_cache:
          keys: 
            - bundle
      - run:
          name: bundle update
          command: |
            bundle config --local path vendor/bundle
            bundle update --jobs=4 --retry=3
            bundle clean --force
      - save_cache:
          key: bundle
          paths: [~/project/vendor/bundle]
      - run: bundle exec rake

workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby_version:
                - "2.7"
